### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by UnsolvedCypher** [ErnaneJ/svelte-star-rating#13]
Hello, thanks for this great project! When I try to build it, it's failing in the rollup:
```
➜  svelte-star-rating git:(main) ✗ npm run build

> @ernane/svelte-star-rating@1.1.5 build
> rollup -c


src/AtButton.svelte → dist/index.mjs, dist/index.js...
[!] Error: Could not resolve entry module (src/AtButton.svelte).
Error: Could not resolve entry module (src/AtButton.svelte).
    at error (/Users/mmcmillan/git/superapp/node_modules/.pnpm/@ernane+svelte-star-rating@1.1.5/node_modules/@ernane/svelte-star-rating/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.loadEntryModule (/Users/mmcmillan/git/superapp/node_modules/.pnpm/@ernane+svelte-star-rating@1.1.5/node_modules/@ernane/svelte-star-rating/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:22306:20)
    at async Promise.all (index 0)
```

It seems that the rollup configuration is pointing at `src/AtButton.svelte` which doesn't exist.

**Comment by ErnaneJ** [comment]
Ah thank you! This may have been missed in an earlier version. I believe this has been resolved in the latest version. Check on version [v1.1.6](https://github.com/ErnaneJ/svelte-star-rating/releases/tag/v1.1.6). Thank you again for your attention to this matter! 🫂
